package gui.supAdmin;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import model.MySQL;

/**
 *
 * @author kguna
 */
public class ManageEmployeeAttendance extends javax.swing.JPanel {

    private SuperAdminDashBoard SuperAdminDashBoard;
    private TotalAttendEmployeesDotChart totalEmployeeChart;

    public ManageEmployeeAttendance(SuperAdminDashBoard SuperAdminDashBoard) {
        initComponents();
        addTotalEmployeeDotChart();
        loadEmployeeAttendanceDetails();
        this.SuperAdminDashBoard = SuperAdminDashBoard;
    }

    public void resetAll() {

        jTextField2.setText("");
        jLabel21.setText("");
        jLabel22.setText("");
        jLabel23.setText("");
        jLabel24.setText("");
        jLabel12.setText("");
    }

    public void addTotalEmployeeDotChart() {
        totalEmployeeChart = new TotalAttendEmployeesDotChart(this);
        jPanel23.add(totalEmployeeChart, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(jPanel23);
    }

    private void textFieldcomponentRearrange(JTextField targetComponent) {
        ArrayList<String> characterArray = new ArrayList<>(Arrays.asList(targetComponent.getText().split("")));
        characterArray.remove(characterArray.size() - 1);
        targetComponent.setText(String.join("", characterArray));
    }

    public void loadEmployeeAttendanceDetails() {
        try {

            ResultSet employeeAttendanceCountResultset = MySQL.execute("SELECT COUNT(`employee_employee_nic`) FROM `employee_attendance` INNER JOIN `attendance_date` ON "
                    + "`employee_attendance`.`attendance_date_attendance_date_id`=`attendance_date`.`attendance_date_id` INNER JOIN `employee_attendance_status` ON "
                    + "`employee_attendance`.`employee_attendance_status_employee_attendance_status_id`=`employee_attendance_status`.`employee_attendance_status_id` "
                    + "WHERE `attendance_date` ='" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()) + "' AND `employee_attendance_status_name`='Present'");

            ResultSet totalActiveEmployeeCountResultset = MySQL.execute("SELECT COUNT(`employee_nic`) From `employee` INNER JOIN `employee_status` ON "
                    + "`employee`.`employee_status_employee_status_id`=`employee_status`.`employee_status_id` "
                    + "WHERE `employee_status_name`='Active'");

            
            if (totalActiveEmployeeCountResultset.next()) {
                jLabel18.setText(totalActiveEmployeeCountResultset.getString("COUNT(`employee_nic`)"));
            } else {
                jLabel18.setText("Still Checking......");
            }
            if (employeeAttendanceCountResultset.next()) {
                jLabel25.setText(employeeAttendanceCountResultset.getString("COUNT(`employee_employee_nic`)"));
            } else {
                jLabel25.setText("0");
            }
            

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel44 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel17 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(949, 36));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(513, 80));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/iconPack24/image_accept.png"))); // NOI18N
        jLabel1.setText("Mark Employee Attendance");
        jPanel7.add(jLabel1, java.awt.BorderLayout.CENTER);
        jPanel7.add(jSeparator2, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jPanel6.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/iconPack24/refresh.png"))); // NOI18N
        jButton5.setText("Reset All");
        jButton5.setToolTipText("Reset All");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/iconPack24/back.png"))); // NOI18N
        jButton4.setText("Go Back");
        jButton4.setToolTipText("Go Back");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);

        jPanel7.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(949, 400));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(749, 31));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("segoe ui", 1, 12)); // NOI18N
        jButton1.setText("Arrange Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, java.awt.BorderLayout.LINE_START);
        jPanel8.add(jSeparator1, java.awt.BorderLayout.PAGE_END);

        jPanel44.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("segoe ui", 1, 12)); // NOI18N
        jButton3.setText("Finalyze");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel44.add(jButton3, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel44, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel16.setPreferredSize(new java.awt.Dimension(300, 368));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.BorderLayout());

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel15.add(jSeparator4, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel15, java.awt.BorderLayout.LINE_START);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel29.setPreferredSize(new java.awt.Dimension(296, 200));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(296, 10));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel29.add(jPanel32, java.awt.BorderLayout.PAGE_START);

        jPanel35.setLayout(new java.awt.BorderLayout());

        jPanel36.setPreferredSize(new java.awt.Dimension(296, 30));
        jPanel36.setLayout(new java.awt.BorderLayout());

        jLabel16.setFont(new java.awt.Font("segoe ui", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Summary");
        jLabel16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel36.add(jLabel16, java.awt.BorderLayout.PAGE_START);

        jPanel35.add(jPanel36, java.awt.BorderLayout.PAGE_START);

        jPanel40.setLayout(new java.awt.GridLayout(4, 1));

        jPanel39.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("segoe ui", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel39.add(jLabel18, java.awt.BorderLayout.LINE_END);

        jLabel20.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Total Employees Count : ");
        jLabel20.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel39.add(jLabel20, java.awt.BorderLayout.CENTER);

        jPanel40.add(jPanel39);

        jPanel41.setLayout(new java.awt.BorderLayout());

        jLabel25.setFont(new java.awt.Font("segoe ui", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setPreferredSize(new java.awt.Dimension(100, 16));
        jPanel41.add(jLabel25, java.awt.BorderLayout.LINE_END);

        jLabel26.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Total Attend Count Today : ");
        jLabel26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel41.add(jLabel26, java.awt.BorderLayout.CENTER);

        jPanel40.add(jPanel41);

        jPanel42.setLayout(new java.awt.BorderLayout());
        jPanel40.add(jPanel42);

        jPanel43.setLayout(new java.awt.BorderLayout());
        jPanel40.add(jPanel43);

        jPanel35.add(jPanel40, java.awt.BorderLayout.CENTER);

        jPanel29.add(jPanel35, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel29, java.awt.BorderLayout.PAGE_END);

        jPanel30.setPreferredSize(new java.awt.Dimension(296, 41));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("segoe ui", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Emplopyee Details");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel30.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jPanel17.add(jPanel30, java.awt.BorderLayout.PAGE_START);

        jPanel31.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(296, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jSeparator5, java.awt.BorderLayout.CENTER);

        jPanel31.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel33.setLayout(new java.awt.BorderLayout());

        jPanel34.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        jPanel34.setPreferredSize(new java.awt.Dimension(100, 157));
        jPanel34.setLayout(new java.awt.GridLayout(5, 1));

        jLabel13.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Name : ");
        jPanel34.add(jLabel13);

        jLabel14.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Job Position : ");
        jPanel34.add(jLabel14);

        jLabel17.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Mobile : ");
        jPanel34.add(jLabel17);

        jLabel15.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Email : ");
        jPanel34.add(jLabel15);

        jLabel19.setFont(new java.awt.Font("segoe ui", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Joined Date : ");
        jPanel34.add(jLabel19);

        jPanel33.add(jPanel34, java.awt.BorderLayout.LINE_START);

        jPanel38.setPreferredSize(new java.awt.Dimension(260, 157));
        jPanel38.setLayout(new java.awt.GridLayout(5, 1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.add(jLabel21);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.add(jLabel23);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.add(jLabel22);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.add(jLabel12);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel38.add(jLabel24);

        jPanel33.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel31.add(jPanel33, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel31, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel16, java.awt.BorderLayout.LINE_END);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel18.setPreferredSize(new java.awt.Dimension(433, 41));
        jPanel18.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel45, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel46, java.awt.BorderLayout.LINE_END);

        jPanel47.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jPanel47.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("segoe ui", 1, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/iconPack24/search.png"))); // NOI18N
        jLabel2.setText("NIC   ");
        jPanel47.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jButton6.setText("Mark Attendance");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel47.add(jButton6, java.awt.BorderLayout.LINE_END);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel47.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel47, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(10, 272));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel14.setPreferredSize(new java.awt.Dimension(647, 10));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel12.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        jPanel21.setPreferredSize(new java.awt.Dimension(10, 362));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel21, java.awt.BorderLayout.LINE_START);

        jPanel22.setPreferredSize(new java.awt.Dimension(647, 10));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel22, java.awt.BorderLayout.PAGE_END);

        jPanel23.setLayout(new java.awt.BorderLayout());
        jPanel12.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel28.setLayout(new java.awt.BorderLayout());
        add(jPanel28, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int resetAllBtn = JOptionPane.showConfirmDialog(this, "Are you sure want to reset all?", "Reset All", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (resetAllBtn == JOptionPane.YES_OPTION) {
            resetAll();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.SuperAdminDashBoard.setJPanelLoad(new EmployeeAttendance(this.SuperAdminDashBoard));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int arrangeAttendance = JOptionPane.showConfirmDialog(this, "Are you sure want to Arrange Attendance Table?", "Arrange Attendance", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (arrangeAttendance == JOptionPane.YES_OPTION) {

            try {
                ResultSet searchDateResultset = MySQL.execute("SELECT * FROM `attendance_date` WHERE `attendance_date`='" + new SimpleDateFormat("yyy-MM-dd").format(new Date()) + "'");
                if (searchDateResultset.next()) {
                    JOptionPane.showMessageDialog(this, "Already Arranged Attendance Report for Today", "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

                    String attendanceId = String.valueOf(System.currentTimeMillis());

                    MySQL.execute("INSERT INTO `attendance_date`(`attendance_date_id`,`attendance_date`) VALUES('" + attendanceId + "','" + new SimpleDateFormat("yyy-MM-dd").format(new Date()) + "')");
                    ResultSet seacrhEmployeeResultset = MySQL.execute("SELECT `employee_nic` FROM `employee` WHERE `employee_status_employee_status_id`='1'");

                    while (seacrhEmployeeResultset.next()) {

                        MySQL.execute("INSERT INTO `employee_attendance`(`in_time`,`out_time`,`employee_employee_nic`,`attendance_date_attendance_date_id`,`employee_attendance_status_employee_attendance_status_id`) "
                                + "VALUES('','','" + seacrhEmployeeResultset.getString("employee_nic") + "','" + attendanceId + "','3')");
                    }
                    JOptionPane.showMessageDialog(this, "Attendance Report Arranged", "Success", JOptionPane.INFORMATION_MESSAGE);

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int arrangeAttendance = JOptionPane.showConfirmDialog(this, "Do You Want to Mark Attendance?", "Mark Attendance", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (arrangeAttendance == JOptionPane.YES_OPTION) {
            if (jTextField2.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "First Enter The NIC Number", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
            if ((!jTextField2.getText().matches("^(?:19|20)?\\d{2}[0-9]{10}|[0-9]{9}[x|X|v|V]$"))) {
                textFieldcomponentRearrange(jTextField2);

            } else {
                try {
                    ResultSet searchAttendanceDateResultset = MySQL.execute("SELECT `attendance_date_id` FROM `attendance_date` WHERE `attendance_date`='" + new SimpleDateFormat("yyy-MM-dd").format(new Date()) + "'");

                    if (searchAttendanceDateResultset.next()) {
                        ResultSet searchEmployeeResultSet = MySQL.execute("SELECT `employee_employee_nic` FROM `employee_attendance` WHERE `employee_employee_nic`='" + jTextField2.getText() + "' AND `attendance_date_attendance_date_id`='" + searchAttendanceDateResultset.getString("attendance_date_id") + "' AND `employee_attendance_status_employee_attendance_status_id`='3'");

                        if (searchEmployeeResultSet.next()) {
                            
                            MySQL.execute("UPDATE `employee_attendance` "
                                    + "SET `in_time` = '" + new SimpleDateFormat("hh:MM:ss").format(new Date()) + "',"
                                    + "`employee_attendance_status_employee_attendance_status_id`='1' "
                                    + "WHERE `employee_employee_nic`='" + searchEmployeeResultSet.getString("employee_employee_nic") + "' AND `attendance_date_attendance_date_id`='" + searchAttendanceDateResultset.getLong("attendance_date_id") + "'");
                            JOptionPane.showMessageDialog(this, "Attendance Marked", "Succes", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            JOptionPane.showMessageDialog(this, "No Such a Active Record In the System", "Warming", JOptionPane.WARNING_MESSAGE);
                        }

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }

            }

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:

        String nic = jTextField2.getText();

        try {

            ResultSet employeeDetailsResultset = MySQL.execute("SELECT * FROM `employee` INNER JOIN `position` ON \n"
                    + "`employee`.`position_position_id`=`position`.`position_id` \n"
                    + "WHERE `employee_nic`='" + nic + "'");

            if (employeeDetailsResultset.next()) {
                String fname = employeeDetailsResultset.getString("first_name");
                String lname = employeeDetailsResultset.getString("last_name");
                String mobile = employeeDetailsResultset.getString("employee_mobile");
                String email = employeeDetailsResultset.getString("email");
                String joinedDate = employeeDetailsResultset.getString("join_date");
                String jobPosition = employeeDetailsResultset.getString("position_name");

                jLabel21.setText(fname + " " + lname);
                jLabel22.setText(mobile);
                jLabel12.setText(email);
                jLabel24.setText(joinedDate);
                jLabel23.setText(jobPosition);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jTextField2KeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int arrangeAttendance = JOptionPane.showConfirmDialog(this, "Do You Want to Set the Leave Time", "Set the Leave Time", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (arrangeAttendance == JOptionPane.YES_OPTION) {
            try {
                ResultSet searchAttendanceDateResultset = MySQL.execute("SELECT `attendance_date_id` FROM `attendance_date` WHERE `attendance_date`='" + new SimpleDateFormat("yyy-MM-dd").format(new Date()) + "'");

                if (searchAttendanceDateResultset.next()) {

                    ResultSet availableEmployeeAttendanceResultset = MySQL.execute("SELECT * FROM `employee_attendance` WHERE `attendance_date_attendance_date_id`='" + searchAttendanceDateResultset.getLong("attendance_date_id") + "'");
                    while (availableEmployeeAttendanceResultset.next()) {

                        String query = "";
                        if (availableEmployeeAttendanceResultset.getString("employee_attendance_status_employee_attendance_status_id").equals("3")) {
                            query = "UPDATE `employee_attendance` SET `employee_attendance_status_employee_attendance_status_id`='2' WHERE `employee_employee_nic`='" + availableEmployeeAttendanceResultset.getString("employee_employee_nic") + "' AND `attendance_date_attendance_date_id`='" + searchAttendanceDateResultset.getLong("attendance_date_id") + "'";

                        } else if (availableEmployeeAttendanceResultset.getString("employee_attendance_status_employee_attendance_status_id").equals("1")) {

                            query = "UPDATE `employee_attendance` SET `out_time` = '" + new SimpleDateFormat("hh:MM:ss").format(new Date()) + "' WHERE `employee_employee_nic`='" + availableEmployeeAttendanceResultset.getString("employee_employee_nic") + "' AND `attendance_date_attendance_date_id`='" + searchAttendanceDateResultset.getLong("attendance_date_id") + "'";

                        }
                        if (!query.isEmpty()) {
                            try {
                                MySQL.execute(query);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }

                    JOptionPane.showMessageDialog(this, "All Attendance Records are Finalyzed", "Success", JOptionPane.INFORMATION_MESSAGE);

                }

            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
