/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.supAdmin;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.SymbolAxis;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.LookupPaintScale;
import org.jfree.chart.renderer.xy.XYBlockRenderer;
import org.jfree.chart.title.PaintScaleLegend;
import org.jfree.chart.ui.RectangleEdge;
import org.jfree.chart.ui.RectangleInsets;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.DefaultXYZDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYZDataset;

/**
 *
 * @author kguna
 */
public class TotalAttendEmployeesDotChart extends javax.swing.JPanel {

    private ManageEmployeeAttendance forEmployeeDotChart;

    /**
     * Creates new form TotalAttendEmployeesDotChart
     */
    public TotalAttendEmployeesDotChart(ManageEmployeeAttendance toEmployeeDotChart) {
        initComponents();
        this.forEmployeeDotChart = toEmployeeDotChart;
        loadEmployeeDotChart();
    }

    public void loadEmployeeDotChart() {
        ChartPanel chartPanel = new ChartPanel(createChart(createDataset()));
        jPanel5.add(chartPanel, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(jPanel5);
    }

    private static JFreeChart createChart(XYDataset xyset) {

        NumberAxis xAxis = new NumberAxis("X");
        xAxis.setVisible(false);

        NumberAxis yAxis = new NumberAxis("Y");
        yAxis.setAutoRangeIncludesZero(true);
        yAxis.setInverted(false);
        yAxis.setVisible(false);
        yAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());

        XYBlockRenderer renderer = new XYBlockRenderer();
        renderer.setBlockHeight(1.1);
        renderer.setBlockWidth(1.5);
        LookupPaintScale paintScale = new LookupPaintScale(0.5, 1.0,
                Color.YELLOW);
        paintScale.add(0.5, new Color(50, 51, 51));
        paintScale.add(1.25, new Color(50, 51, 51));
        renderer.setPaintScale(paintScale);
        XYPlot plot = new XYPlot(xyset, xAxis, yAxis, renderer);
        plot.setBackgroundPaint(Color.lightGray);
        plot.setDomainGridlinePaint(new Color(50, 51, 51));
        plot.setRangeGridlinePaint(new Color(50, 51, 51));
        plot.setForegroundAlpha(0.66f);
        plot.setAxisOffset(new RectangleInsets(5, 5, 5, 5));

        JFreeChart jfreechart = new JFreeChart("Employee Attendance Summary", plot);
        jfreechart.removeLegend();
        jfreechart.getTitle().setPaint(new Color(194, 185, 184));
        SymbolAxis scaleAxis = new SymbolAxis(null, new String[]{""});
        scaleAxis.setRange(0.5, 3.5);
        scaleAxis.setPlot(new PiePlot());
        scaleAxis.setGridBandsVisible(false);
        PaintScaleLegend psl = new PaintScaleLegend(paintScale, scaleAxis);
        psl.setAxisOffset(5.0);
        psl.setPosition(RectangleEdge.BOTTOM);
        psl.setMargin(new RectangleInsets(5, 5, 5, 5));
        jfreechart.addSubtitle(psl);
        jfreechart.setBackgroundPaint(new Color(50, 51, 51));
        return jfreechart;

    }

    private static void setValue(double data[][], int i, int j) {
        data[0][(j - 8) * 60 + i] = i;
        data[1][(j - 8) * 60 + i] = j;
    }

    private static XYDataset createDataset() {
        double ad[] = new double[62];
        double ad1[] = new double[62];
        double[][] data = new double[][]{ad, ad1};

        for (int i = 0; i < 60; i++) {
            double jValue = (60 + 480 - i) / 60;
            
//            System.out.println((int) jValue + " " + i);
            
            setValue(data, i, (int) jValue);
        }

        DefaultXYDataset xyset = new DefaultXYDataset();
        xyset.addSeries("Series 1", data);
        return xyset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(647, 378));
        setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(627, 358));
        jPanel5.setLayout(new java.awt.BorderLayout());
        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
